// Menú oficial de El Hornero, transcrito del PDF "Menu hornero 2026" (32 páginas).
// Los precios del menú YA INCLUYEN IMPUESTOS: el sitio no debe volver a sumar IVA.
// Generado el 2026-09-12. Fuente: Menu_Hornero_2026.pdf en la raíz del proyecto.

export const CATS = [
  { key: "Pizzas", img: "/assets/cat-pizzas.png" },
  { key: "Hamburguesas y chivitos", img: "/assets/cat-fuertes.png" },
  { key: "Platos fuertes", img: "/assets/cat-fuertes.png" },
  { key: "Entradas y papas", img: "/assets/cat-empezar.png" },
  { key: "Ensaladas y bowls", img: "/assets/cat-acompanantes.png" },
  { key: "Combos y promos", img: "/assets/cat-combos.png" },
  { key: "Menú infantil", img: "/assets/cat-infantil.png" },
  { key: "Desayunos", img: "/assets/cat-temporada.png" },
  { key: "Postres", img: "/assets/cat-ofertas.png" },
  { key: "Bebidas", img: "/assets/cat-acompanantes.png" },
]

export const MENU = [
  { id: "medio-pollo-receta-especial", cat: "Platos fuertes", sub: "Pollo", name: "Medio pollo receta especial", price: 9.5, desc: "Incluye papas fritas o cocidas." },
  { id: "pollo-entero-receta-especial", cat: "Platos fuertes", sub: "Pollo", name: "Pollo entero receta especial", price: 16.65, desc: "Incluye papas fritas o cocidas." },
  { id: "ensalada-tradicional", cat: "Ensaladas y bowls", sub: "Ensaladas", name: "Ensalada Tradicional", price: 5.4, desc: "Tomate, cebolla, pimiento, lechuga y albahaca." },
  { id: "ensalada-el-hornero", cat: "Ensaladas y bowls", sub: "Ensaladas", name: "Ensalada El Hornero", price: 7.9, desc: "Tomate, queso mozzarella, pimiento rojo, aceituna, tocino, albahaca y lechuga." },
  { id: "ensalada-rucula-manzana", cat: "Ensaladas y bowls", sub: "Ensaladas", name: "Ensalada Rúcula & manzana", price: 6.99, desc: "Rúcula, manzana caramelizada y champiñones con queso parmesano." },
  { id: "ensalada-especial", cat: "Ensaladas y bowls", sub: "Ensaladas", name: "Ensalada Especial", price: 7.4, desc: "Queso mozzarella, jamón, aceitunas, champiñones, choclo, lechuga, tomate, cebolla y pimiento." },
  { id: "bolw-cesar-hornero", cat: "Ensaladas y bowls", sub: "Bowl César Hornero", name: "Bolw Cesár Hornero", price: 6.5, desc: "La mezcla perfecta de lechuga, salsa italiana, cebolla blanca, pollo, garbanzo y nuestro queso parmesano." },
  { id: "spaghetti", cat: "Platos fuertes", sub: "Pastas", name: "Spaghetti", price: 7.15, desc: "Selecciona tu salsa favorita: Pesto, Bolognesa, Napolitana." },
  { id: "lasagnas", cat: "Platos fuertes", sub: "Pastas", name: "Lasagnas", price: 8.8, desc: "Escoge tu sabor: Carne, Pollo, Ricotta y espinaca." },
  { id: "milanesa-especial", cat: "Platos fuertes", sub: "Milanesas", name: "Milanesa especial", price: 12.8, desc: "Milanesa de carne o pollo con queso mozzarella, jamón, pimiento, tocino, papas fritas, arroz y ensalada." },
  { id: "milanesa-napolitana", cat: "Platos fuertes", sub: "Milanesas", name: "Milanesa Napolitana", price: 12.6, desc: "Milanesa de carne o pollo con queso mozzarella, jamón, salsa napolitana papas fritas, arroz y ensalada." },
  { id: "milanesa-a-caballo", cat: "Platos fuertes", sub: "Milanesas", name: "Milanesa a Caballo", price: 11.1, desc: "Milanesa de carne o pollo con dos huevos fritos, papas fritas, arroz y ensalada." },
  { id: "milanesa", cat: "Platos fuertes", sub: "Milanesas", name: "Milanesa", price: 9.75, desc: "Milanesa de carne o pollo con papas fritas, arroz y ensalada." },
  { id: "churrasco-a-caballo", cat: "Platos fuertes", sub: "Milanesas", name: "Churrasco a caballo", price: 17.2, desc: "Lomo, dos huevos fritos, papas fritas arroz y ensalada" },
  { id: "chuleta-ahumada", cat: "Platos fuertes", sub: "Milanesas", name: "Chuleta ahumada", price: 14.6, desc: "Dos chuletas con papas fritas arroz y ensalada." },
  { id: "agrega-salsa-de-pina", cat: "Platos fuertes", sub: "Milanesas", name: "Agrega salsa de piña", price: 1.0, desc: "", extra: true },
  { id: "carne-a-la-piedra", cat: "Platos fuertes", sub: "Carne a la piedra", name: "Carne a la piedra", price: 19.25, desc: "Bife de chorizo 320 gramos, acompañado de papas fritas o cocidas con coliflor, brócoli y pimientos." },
  { id: "americano", cat: "Desayunos", sub: "Desayunos", name: "Americano", price: 8.99, desc: "Cuatro pancakes con mascarpone, dos huevos al gusto, frutillas y granola." },
  { id: "frutero", cat: "Desayunos", sub: "Desayunos", name: "Frutero", price: 6.99, desc: "Ensalada de frutas, mascarpone con granola y frutillas." },
  { id: "criollo", cat: "Desayunos", sub: "Desayunos", name: "Criollo", price: 10.75, desc: "Cazuela de choclo, cebolla, tocino, queso ricotta con huevo frito y mascarpone con granola y frutillas." },
  { id: "tigrillo-hornero", cat: "Desayunos", sub: "Desayunos", name: "Tigrillo Hornero", price: 7.99, desc: "Tigrillo de verde con queso ricotta, mozzarella, contiene tocino, huevo y especias de la casa." },
  { id: "hornero", cat: "Desayunos", sub: "Desayunos", name: "Hornero", price: 8.7, desc: "Sánduche de lomo, tocino y huevo frito con mozzarella gratinado." },
  { id: "provoleta-ahumada", cat: "Entradas y papas", sub: "Entradas", name: "Provoleta ahumada", price: 6.15, desc: "Queso provolone acompañado de nuestras salsas y palitos." },
  { id: "pan-de-ajo", cat: "Entradas y papas", sub: "Entradas", name: "Pan de ajo", price: 2.4, desc: "" },
  { id: "berenjena-a-la-parmesana", cat: "Entradas y papas", sub: "Entradas", name: "Berenjena a la parmesana", price: 5.35, desc: "" },
  { id: "papas-fritas-o-cocinadas", cat: "Entradas y papas", sub: "Entradas", name: "Papas fritas o cocinadas", price: 3.85, desc: "" },
  { id: "alitas-hornero", cat: "Entradas y papas", sub: "Entradas", name: "Alitas Hornero", price: 6.75, desc: "" },
  { id: "provolone-apanado-a-la-piedr", cat: "Entradas y papas", sub: "Entradas", name: "Provolone apanado a la piedra con chutney de piña", price: 6.35, desc: "" },
  { id: "sopa-de-cebolla-gratinada", cat: "Entradas y papas", sub: "Entradas", name: "Sopa de cebolla gratinada", price: 4.1, desc: "" },
  { id: "sopa-de-pollo", cat: "Entradas y papas", sub: "Entradas", name: "Sopa de pollo", price: 4.1, desc: "" },
  { id: "pizza-amsterdam", cat: "Pizzas", sub: "Pizzas de la casa", name: "Pizza Ámsterdam", price: 4.0, desc: "Dos huevos fritos, queso y salsa napolitana", sizes: [{"t": "S", "p": 4.0}] },
  { id: "flamenca", cat: "Pizzas", sub: "Pizzas de la casa", name: "Flamenca", price: 11.25, desc: "Tocino, ciruela pasa, un toque de albahaca y nuestro queso mozzarella.", sizes: [{"t": "M", "p": 11.25}] },
  { id: "pesto-3-quesos", cat: "Pizzas", sub: "Pizzas de la casa", name: "Pesto 3 quesos", price: 11.25, desc: "Queso ricotta, parmesano y mozzarella, acompañada de pesto.", sizes: [{"t": "M", "p": 11.25}] },
  { id: "pizza-genovesa", cat: "Pizzas", sub: "Pizzas de la casa", name: "Pizza Genovesa", price: 11.25, desc: "Queso mozzarella, tomate deshidratado y rúcula , acompañada de una burrata.", sizes: [{"t": "M", "p": 11.25}] },
  { id: "1-ingrediente", cat: "Pizzas", sub: "Tu creación", name: "1 ingrediente", price: 9.55, desc: "", sizes: [{"t": "S", "p": 4.05}, {"t": "M", "p": 9.55}, {"t": "L", "p": 15.3}, {"t": "XL", "p": 20.75}, {"t": "XXL", "p": 26.15}] },
  { id: "ingrediente-adicional", cat: "Pizzas", sub: "Tu creación", name: "Ingrediente adicional", price: 1.95, desc: "", sizes: [{"t": "S", "p": 1.2}, {"t": "M", "p": 1.95}, {"t": "L", "p": 2.99}, {"t": "XL", "p": 3.6}, {"t": "XXL", "p": 4.7}], extra: true },
  { id: "extra-queso", cat: "Pizzas", sub: "Tu creación", name: "Extra queso", price: 3.05, desc: "", sizes: [{"t": "S", "p": 1.45}, {"t": "M", "p": 3.05}, {"t": "L", "p": 4.2}, {"t": "XL", "p": 5.95}, {"t": "XXL", "p": 7.6}], extra: true },
  { id: "criolla", cat: "Pizzas", sub: "Combinadas", name: "Criolla", price: 11.15, desc: "Tocino y choclo", sizes: [{"t": "S", "p": 4.9}, {"t": "M", "p": 11.15}, {"t": "L", "p": 17.9}, {"t": "XL", "p": 22.8}, {"t": "XXL", "p": 29.85}] },
  { id: "hawaiana", cat: "Pizzas", sub: "Combinadas", name: "Hawaiana", price: 11.15, desc: "Jamón y piña", sizes: [{"t": "S", "p": 4.9}, {"t": "M", "p": 11.15}, {"t": "L", "p": 17.9}, {"t": "XL", "p": 22.8}, {"t": "XXL", "p": 29.85}] },
  { id: "jamon-y-champinones", cat: "Pizzas", sub: "Combinadas", name: "Jamón y champiñones", price: 11.15, desc: "", sizes: [{"t": "S", "p": 4.9}, {"t": "M", "p": 11.15}, {"t": "L", "p": 17.9}, {"t": "XL", "p": 22.8}, {"t": "XXL", "p": 29.85}] },
  { id: "pepperoni-especial", cat: "Pizzas", sub: "Combinadas", name: "Pepperoni especial", price: 11.15, desc: "", sizes: [{"t": "S", "p": 4.9}, {"t": "M", "p": 11.15}, {"t": "L", "p": 17.9}, {"t": "XL", "p": 22.8}, {"t": "XXL", "p": 29.85}] },
  { id: "uruguaya", cat: "Pizzas", sub: "Sugeridas", name: "Uruguaya", price: 5.85, desc: "Salsa de tomate frescos y orégano (sin queso)", sizes: [{"t": "S", "p": 2.8}, {"t": "M", "p": 5.85}, {"t": "L", "p": 9.55}, {"t": "XL", "p": 12.8}, {"t": "XXL", "p": 15.9}] },
  { id: "napolitana", cat: "Pizzas", sub: "Sugeridas", name: "Napolitana", price: 8.9, desc: "Tomate en rodajas y orégano", sizes: [{"t": "S", "p": 3.9}, {"t": "M", "p": 8.9}, {"t": "L", "p": 15.25}, {"t": "XL", "p": 20.75}, {"t": "XXL", "p": 26.35}] },
  { id: "maqueno", cat: "Pizzas", sub: "Sugeridas", name: "Maqueño", price: 8.9, desc: "Maqueño y queso", sizes: [{"t": "S", "p": 3.9}, {"t": "M", "p": 8.9}, {"t": "L", "p": 15.25}, {"t": "XL", "p": 20.75}, {"t": "XXL", "p": 26.35}] },
  { id: "mozzarella", cat: "Pizzas", sub: "Sugeridas", name: "Mozzarella", price: 8.9, desc: "Queso y orégano", sizes: [{"t": "S", "p": 3.9}, {"t": "M", "p": 8.9}, {"t": "L", "p": 15.25}, {"t": "XL", "p": 20.75}, {"t": "XXL", "p": 26.35}] },
  { id: "el-hornero", cat: "Pizzas", sub: "Especialidades", name: "El Hornero", price: 15.3, desc: "Jamón, salami, tocino y pimiento", sizes: [{"t": "S", "p": 6.15}, {"t": "M", "p": 15.3}, {"t": "L", "p": 24.4}, {"t": "XL", "p": 29.9}, {"t": "XXL", "p": 38.4}] },
  { id: "super-criolla", cat: "Pizzas", sub: "Especialidades", name: "Súper criolla", price: 15.3, desc: "Choclo, tocino, ají de tomate de árbol con chochos y cebolla", sizes: [{"t": "S", "p": 6.15}, {"t": "M", "p": 15.3}, {"t": "L", "p": 24.4}, {"t": "XL", "p": 29.9}, {"t": "XXL", "p": 38.4}] },
  { id: "tropical-de-pollo", cat: "Pizzas", sub: "Especialidades", name: "Tropical de pollo", price: 15.3, desc: "Pollo BBQ, piña y pimiento rojo", sizes: [{"t": "S", "p": 6.15}, {"t": "M", "p": 15.3}, {"t": "L", "p": 24.4}, {"t": "XL", "p": 29.9}, {"t": "XXL", "p": 38.4}] },
  { id: "pepperonata", cat: "Pizzas", sub: "Especialidades", name: "Pepperonata", price: 15.3, desc: "Pimiento rojo y verde, tocino y champiñones. Todo al ajillo", sizes: [{"t": "S", "p": 6.15}, {"t": "M", "p": 15.3}, {"t": "L", "p": 24.4}, {"t": "XL", "p": 29.9}, {"t": "XXL", "p": 38.4}] },
  { id: "exclusiva", cat: "Pizzas", sub: "Especialidades", name: "Exclusiva", price: 15.3, desc: "Salami, salchicha, cebolla, pimientos y champiñones", sizes: [{"t": "S", "p": 6.15}, {"t": "M", "p": 15.3}, {"t": "L", "p": 24.4}, {"t": "XL", "p": 29.9}, {"t": "XXL", "p": 38.4}] },
  { id: "vegetariana", cat: "Pizzas", sub: "Especialidades", name: "Vegetariana", price: 15.3, desc: "Champiñones, aceitunas, pimiento, cebolla y choclo", sizes: [{"t": "S", "p": 6.15}, {"t": "M", "p": 15.3}, {"t": "L", "p": 24.4}, {"t": "XL", "p": 29.9}, {"t": "XXL", "p": 38.4}] },
  { id: "todo-carnes", cat: "Pizzas", sub: "Especialidades", name: "Todo carnes", price: 15.3, desc: "Jamón, salami, salchicha, carne y tocino", sizes: [{"t": "S", "p": 6.15}, {"t": "M", "p": 15.3}, {"t": "L", "p": 24.4}, {"t": "XL", "p": 29.9}, {"t": "XXL", "p": 38.4}] },
  { id: "hamburguesa-provolone", cat: "Hamburguesas y chivitos", sub: "Hamburguesas", name: "Hamburguesa provolone", price: 8.8, desc: "Queso provolone, rúcula, chutney de piña y papas fritas." },
  { id: "hamburguesa-hornero", cat: "Hamburguesas y chivitos", sub: "Hamburguesas", name: "Hamburguesa Hornero", price: 8.5, desc: "Deliciosa y única mermelada de tocino con queso mozzarella y papas fritas." },
  { id: "hamburguesa-vegetariana", cat: "Hamburguesas y chivitos", sub: "Hamburguesas", name: "Hamburguesa Vegetariana", price: 7.99, desc: "Proteína a base de arveja con salsa de champiñones, cebolla salteada, queso mozzarella y papas fritas." },
  { id: "extra-queso-2", cat: "Hamburguesas y chivitos", sub: "Hamburguesas", name: "Extra queso", price: 0.75, desc: "", extra: true },
  { id: "mermelada-de-tocino", cat: "Hamburguesas y chivitos", sub: "Hamburguesas", name: "Mermelada de tocino", price: 1.0, desc: "", extra: true },
  { id: "extra-carne", cat: "Hamburguesas y chivitos", sub: "Hamburguesas", name: "Extra carne", price: 1.55, desc: "", extra: true },
  { id: "gaseosa-desechable", cat: "Hamburguesas y chivitos", sub: "Hamburguesas", name: "Gaseosa desechable", price: 2.3, desc: "" },
  { id: "chivito-de-pollo", cat: "Hamburguesas y chivitos", sub: "Chivitos", name: "Chivito de pollo", price: 7.99, desc: "Filete de pechuga de pollo, champiñones, pimiento, tomate y queso mozzarella." },
  { id: "chivito-completo", cat: "Hamburguesas y chivitos", sub: "Chivitos", name: "Chivito completo", price: 9.5, desc: "Lomo fino, tocino, queso mozzarella, pimiento, lechuga, jamón y tomate." },
  { id: "chivito-mozzarella", cat: "Hamburguesas y chivitos", sub: "Chivitos", name: "Chivito mozzarella", price: 7.5, desc: "Lomo fino, lechuga, tomate y queso mozzarella." },
  { id: "anade-papas", cat: "Hamburguesas y chivitos", sub: "Chivitos", name: "Añade papas", price: 2.05, desc: "", extra: true },
  { id: "anade-extra-queso", cat: "Hamburguesas y chivitos", sub: "Chivitos", name: "Añade extra queso", price: 1.45, desc: "", extra: true },
  { id: "festin-hornero", cat: "Combos y promos", sub: "Festín Hornero", name: "Festín Hornero", price: 26.99, desc: "Medio pollo Hornero, pizza de especialidad 10 pedazos, 2 hamburguesas mini, papas cheddar y tocino y una jarra de bebida." },
  { id: "hamburguesa-infantil", cat: "Menú infantil", sub: "Menú infantil", name: "Hamburguesa Infantil", price: 5.99, desc: "Hamburguesa infantil, papas fritas, bebida y sorpresa." },
  { id: "combo-1", cat: "Menú infantil", sub: "Menú infantil", name: "Combo 1", price: 5.99, desc: "Pizza infantil, bebida, papas y sorpresa." },
  { id: "combo-2", cat: "Menú infantil", sub: "Menú infantil", name: "Combo 2", price: 5.99, desc: "Pizza personal, bebida y sorpresa." },
  { id: "combo-3", cat: "Menú infantil", sub: "Menú infantil", name: "Combo 3", price: 5.99, desc: "Spaghetti, bebida y sorpresa." },
  { id: "combo-4", cat: "Menú infantil", sub: "Menú infantil", name: "Combo 4", price: 5.99, desc: "Deditos de pollo, bebida, papas fritas y sorpresa." },
  { id: "combo-5", cat: "Menú infantil", sub: "Menú infantil", name: "Combo 5", price: 5.99, desc: "Hamburguesa infantil, papas fritas, bebida y sorpresa." },
  { id: "peluche-de-alberto", cat: "Menú infantil", sub: "Menú infantil", name: "Peluche de Alberto", price: 3.6, desc: "" },
  { id: "pizza-precocida", cat: "Combos y promos", sub: "Pizza Precocida", name: "Pizza Precocida", price: 5.99, desc: "Hornéala en familia. Una pizza de 16 pedazos de 1 ingrediente. Prepárala en horno." },
  { id: "combo-perfecto-con-coca-cola", cat: "Combos y promos", sub: "Combo perfecto", name: "Combo perfecto con Coca-Cola", price: 22.5, desc: "20 pedazos + 1 jarra de Coca Cola. Una pizza de 10 pedazos Todo Carnes y una pizza de 10 pedazos de Jamón y Champiñones + papas + jarra de gaseosa a elección (Sprite o Coca Cola)." },
  { id: "mega-xl", cat: "Combos y promos", sub: "Mega XL", name: "MEGA XL", price: 38.99, desc: "Elige tus cuatro sabores. 2 especialidad y 2 combinada. 1.2 metros, 48 pedazos." },
  { id: "el-nevado", cat: "Postres", sub: "Postres", name: "El Nevado", price: 6.65, desc: "Una montaña de sabores, base de brownie con crema chantilly, banano, helado de vainilla, cubierto de chocolate líquido." },
  { id: "mousse-de-cafe", cat: "Postres", sub: "Postres", name: "Mousse de Café", price: 4.2, desc: "" },
  { id: "mascarpone-con-frutillas", cat: "Postres", sub: "Postres", name: "Mascarpone con frutillas", price: 3.6, desc: "" },
  { id: "mousse-de-chocolate", cat: "Postres", sub: "Postres", name: "Mousse de chocolate", price: 3.7, desc: "" },
  { id: "cheesecake-de-limon", cat: "Postres", sub: "Postres", name: "Cheesecake de limón", price: 4.0, desc: "" },
  { id: "tiramisu", cat: "Postres", sub: "Postres", name: "Tiramisú", price: 4.0, desc: "" },
  { id: "copa-de-helado-2-sabores", cat: "Postres", sub: "Postres", name: "Copa de helado (2 sabores)", price: 3.6, desc: "" },
  { id: "bananas-con-crema", cat: "Postres", sub: "Postres", name: "Bananas con crema", price: 3.5, desc: "" },
  { id: "frutillas-con-crema", cat: "Postres", sub: "Postres", name: "Frutillas con crema", price: 3.5, desc: "" },
  { id: "ensalada-de-frutas", cat: "Postres", sub: "Postres", name: "Ensalada de frutas", price: 3.9, desc: "" },
  { id: "cheesecake-hornero", cat: "Postres", sub: "Postres", name: "Cheesecake Hornero", price: 4.6, desc: "" },
  { id: "flan-de-leche-casero", cat: "Postres", sub: "Postres", name: "Flan de leche casero", price: 3.6, desc: "Elaborado con vainilla natural." },
  { id: "milkshake", cat: "Postres", sub: "Postres", name: "Milkshake", price: 3.1, desc: "Escoge tu sabor: Chocolate, vainilla o frutilla." },
  { id: "nevado", cat: "Postres", sub: "Postres", name: "Nevado", price: 6.65, desc: "Una montaña de sabores, base de brownie con crema chantilly, banano, helado de vainilla, cubierto de chocolate líquido." },
  { id: "brownie-con-helado", cat: "Postres", sub: "Postres", name: "Brownie con helado", price: 4.6, desc: "" },
  { id: "banana-split", cat: "Postres", sub: "Postres", name: "Banana Split", price: 4.8, desc: "" },
  { id: "choco-bagnato", cat: "Postres", sub: "Postres", name: "Choco Bagnato", price: 3.9, desc: "Torta humeda de chocolate." },
  { id: "choco-bagnato-familiar-10-po", cat: "Postres", sub: "Postres", name: "Choco Bagnato Familiar (10 porciones)", price: 20.5, desc: "Torta humeda de chocolate." },
  { id: "capuccino", cat: "Bebidas", sub: "Bebidas", name: "Capuccino", price: 2.65, desc: "" },
  { id: "mocaccino", cat: "Bebidas", sub: "Bebidas", name: "Mocaccino", price: 2.99, desc: "" },
  { id: "chocolate-caliente", cat: "Bebidas", sub: "Bebidas", name: "Chocolate caliente", price: 2.99, desc: "" },
  { id: "infusiones-de-frutas", cat: "Bebidas", sub: "Bebidas", name: "Infusiones de frutas", price: 1.85, desc: "" },
  { id: "cafe-americano", cat: "Bebidas", sub: "Bebidas", name: "Café americano", price: 1.8, desc: "" },
  { id: "cafe-expresso", cat: "Bebidas", sub: "Bebidas", name: "Café expresso", price: 1.8, desc: "" },
  { id: "cafe-helado", cat: "Bebidas", sub: "Bebidas", name: "Café helado", price: 2.99, desc: "" },
  { id: "cafe-con-leche", cat: "Bebidas", sub: "Bebidas", name: "Café con leche", price: 2.1, desc: "" },
  { id: "agua-aromatica-o-te", cat: "Bebidas", sub: "Bebidas", name: "Agua aromática o té", price: 1.8, desc: "" },
  { id: "cerveza", cat: "Bebidas", sub: "Licores", name: "Cerveza", price: 2.99, desc: "" },
  { id: "jarra-de-vino-hervido", cat: "Bebidas", sub: "Licores", name: "Jarra de vino hervido", price: 20.5, desc: "" },
  { id: "copa-de-vino-hervido", cat: "Bebidas", sub: "Licores", name: "Copa de vino hervido", price: 4.0, desc: "" },
  { id: "vino-botella", cat: "Bebidas", sub: "Licores", name: "Vino botella", price: 20.4, desc: "" },
  { id: "copa-de-vino", cat: "Bebidas", sub: "Licores", name: "Copa de vino", price: 3.6, desc: "" },
  { id: "sangria", cat: "Bebidas", sub: "Licores", name: "Sangría", price: 16.9, desc: "" },
  { id: "1-2-sangria", cat: "Bebidas", sub: "Licores", name: "1/2 Sangría", price: 9.15, desc: "" },
  { id: "limonada-de-hierba-buena", cat: "Bebidas", sub: "Limonadas Hornero", name: "Limonada de Hierba buena", price: 2.5, desc: "" },
  { id: "limonada-de-jengibre", cat: "Bebidas", sub: "Limonadas Hornero", name: "Limonada de Jengibre", price: 2.5, desc: "" },
  { id: "limonada-de-coco", cat: "Bebidas", sub: "Bebidas especiales", name: "Limonada de coco", price: 2.99, desc: "" },
  { id: "limonada-de-frutilla-burbuje", cat: "Bebidas", sub: "Bebidas especiales", name: "Limonada de frutilla burbujeante", price: 2.99, desc: "" },
  { id: "fusion-helada-mora-guanabana", cat: "Bebidas", sub: "Bebidas especiales", name: "Fusión helada Mora guanábana", price: 2.99, desc: "" },
  { id: "jugos-varios", cat: "Bebidas", sub: "Bebidas", name: "Jugos varios", price: 2.3, desc: "Mora, naranjilla, guanábana y tomate de árbol." },
  { id: "vaso-de-gaseosa", cat: "Bebidas", sub: "Bebidas", name: "Vaso de gaseosa", price: 1.95, desc: "" },
  { id: "jarra-de-gaseosa-4-personas", cat: "Bebidas", sub: "Bebidas", name: "Jarra de gaseosa (4 personas)", price: 6.65, desc: "" },
  { id: "vaso-de-limonada", cat: "Bebidas", sub: "Bebidas", name: "Vaso de limonada", price: 1.65, desc: "" },
  { id: "jarra-de-limonada-4-personas", cat: "Bebidas", sub: "Bebidas", name: "Jarra de limonada (4 personas)", price: 5.65, desc: "" },
  { id: "vaso-de-te-helado", cat: "Bebidas", sub: "Bebidas", name: "Vaso de té helado", price: 1.65, desc: "" },
  { id: "jarra-de-te-helado-4-persona", cat: "Bebidas", sub: "Bebidas", name: "Jarra de té helado (4 personas)", price: 5.65, desc: "" },
  { id: "agua-mineral", cat: "Bebidas", sub: "Bebidas", name: "Agua mineral", price: 1.55, desc: "" },
  { id: "gaseosa-desechable-2", cat: "Bebidas", sub: "Bebidas", name: "Gaseosa desechable", price: 2.3, desc: "" },
  { id: "papa-italiana", cat: "Entradas y papas", sub: "Papas", name: "Papa Italiana", price: 4.8, desc: "Papas fritas acompañandas con salsa bolognesa y salsa italiana" },
  { id: "papa-hornero", cat: "Entradas y papas", sub: "Papas", name: "Papa Hornero", price: 4.8, desc: "Papas fritas acompañandas con mermelada de tocino y salsa italiana" },
  { id: "papa-champi", cat: "Entradas y papas", sub: "Papas", name: "Papa Champi", price: 4.8, desc: "Papas fritas acompañandas con queso mozzarella y salsa de champiñones" },
]

export const FREE_DELIVERY_OVER = 25
export const DELIVERY_FEE = 2.5
// Los precios ya incluyen IVA (así lo imprime el menú oficial en casi todas sus páginas).
// Se guarda la tasa solo para DESGLOSAR el impuesto ya contenido, nunca para sumarlo.
export const IVA = 0.15
export const PRECIOS_INCLUYEN_IVA = true
export const MASAS = ['Tradicional (12 mm)', 'Fina (8 mm)']
